services:
  cache:
    image: redis
    container_name: charades-app-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-storage:/data

volumes:
  redis-storage: {}
